/*
 *  Copyright 2019 Ortis (ortis@ortis.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package io.ortis.jsafebox.gui.metadata;

import io.ortis.jsafebox.Block;
import io.ortis.jsafebox.gui.Settings;

import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 * @author ortis
 */
public class MetadataPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel binaryViewLabel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JTable metadataTable;
	private javax.swing.JLabel txtViewLabel;
	// End of variables declaration//GEN-END:variables


	/**
	 * Creates new form MetadataPanel
	 */
	public MetadataPanel()
	{
		initComponents();

		final Settings settings = Settings.getSettings();

		this.mainPanel.setBackground(settings.getUITheme().getBackgroundColor());

		this.txtViewLabel.setVisible(false);
		this.binaryViewLabel.setVisible(false);

		this.jScrollPane1.setOpaque(false);
		this.jScrollPane1.setBorder(new EmptyBorder(1, 1, 1, 1));
		this.jScrollPane1.setViewportBorder(null);
		this.jScrollPane1.setBackground(this.mainPanel.getBackground());

		this.jScrollPane1.getViewport().setOpaque(false);
		this.jScrollPane1.getViewport().setBorder(null);
		this.jScrollPane1.getViewport().setBackground(this.mainPanel.getBackground());

		this.metadataTable.setModel(new MetadataTableModel(this.metadataTable));

		final MetadataCellRenderer cellRenderer = new MetadataCellRenderer(settings.getUITheme().getTextLabelColor(), this.mainPanel.getBackground());
		this.metadataTable.setDefaultRenderer(String.class, cellRenderer);
		this.metadataTable.setDefaultRenderer(Integer.class, cellRenderer);
		this.metadataTable.setDefaultRenderer(Double.class, cellRenderer);
		this.metadataTable.setDefaultRenderer(Object.class, cellRenderer);

		this.metadataTable.getTableHeader().setDefaultRenderer(cellRenderer);

		this.metadataTable.setBorder(null);
		this.metadataTable.setAutoCreateRowSorter(true);
		this.metadataTable.setCellSelectionEnabled(false);

		this.metadataTable.setOpaque(false);
		this.metadataTable.setBorder(null);
		this.metadataTable.setBackground(this.mainPanel.getBackground());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		mainPanel = new javax.swing.JPanel();
		txtViewLabel = new javax.swing.JLabel();
		binaryViewLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		metadataTable = new javax.swing.JTable();

		setBorder(null);
		setPreferredSize(new java.awt.Dimension(400, 300));
		setLayout(new java.awt.BorderLayout());

		mainPanel.setBackground(new java.awt.Color(40, 52, 240));
		mainPanel.setBorder(null);

		txtViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt-file-32.png"))); // NOI18N
		txtViewLabel.setToolTipText("View as text");

		binaryViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/binary-file-32.png"))); // NOI18N
		binaryViewLabel.setToolTipText("View as hexadecimal");

		metadataTable.setBackground(new java.awt.Color(22, 28, 38));
		metadataTable.setBorder(null);
		metadataTable.setForeground(new java.awt.Color(243, 241, 241));
		metadataTable.setModel(
				new javax.swing.table.DefaultTableModel(new Object[][]{{"Name", "data.txt"}, {"Type", "text/text"}, {"Length", "1024"}, {null, null}, {null, null}},
						new String[]{"Title 1", "Title 2"}));
		metadataTable.setGridColor(new java.awt.Color(22, 28, 38));
		jScrollPane1.setViewportView(metadataTable);

		javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup().addContainerGap(312, Short.MAX_VALUE).addComponent(
						txtViewLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(binaryViewLabel).addContainerGap()).addGroup(
				mainPanelLayout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE).addGap(
						13, 13, 13)));
		mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				mainPanelLayout.createSequentialGroup().addContainerGap().addGroup(mainPanelLayout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
						javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(binaryViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
						javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE).addContainerGap()));

		add(mainPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents


	public void setBlock(final Block block)
	{
		((MetadataTableModel) this.metadataTable.getModel()).setSafeFile(block);
	}
}
