/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.ortis.jsafebox.gui;

/**
 *
 * @author ortis
 */
public class MetadataPanel extends javax.swing.JPanel {

    /**
     * Creates new form MetadataPanel2
     */
    public MetadataPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        txtViewLabel = new javax.swing.JLabel();
        binaryViewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        metadataTable = new javax.swing.JTable();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(40, 52, 240));
        mainPanel.setBorder(null);

        txtViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt-32.png"))); // NOI18N
        txtViewLabel.setToolTipText("View as text");

        binaryViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/binary-32.png"))); // NOI18N
        binaryViewLabel.setToolTipText("View as hexadecimal");

        metadataTable.setBackground(new java.awt.Color(22, 28, 38));
        metadataTable.setBorder(null);
        metadataTable.setForeground(new java.awt.Color(243, 241, 241));
        metadataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Name", "data.txt"},
                {"Type", "text/text"},
                {"Length", "1024"},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        metadataTable.setGridColor(new java.awt.Color(22, 28, 38));
        jScrollPane1.setViewportView(metadataTable);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(txtViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(binaryViewLabel)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(binaryViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel binaryViewLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable metadataTable;
    private javax.swing.JLabel txtViewLabel;
    // End of variables declaration//GEN-END:variables
}
