/*
 *  Copyright 2019 Ortis (ortis@ortis.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package io.ortis.jsafebox.gui;

import io.ortis.jsafebox.gui.tasks.CreateTask;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.Locale;

/**
 * @author Ortis
 */
public class NewSafeFrame extends javax.swing.JDialog implements MouseListener, ActionListener
{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel password1MetaLabel;
    private javax.swing.JPasswordField password1TextField;
    private javax.swing.JLabel password2MetaLabel;
    private javax.swing.JPasswordField password2TextField;
    private javax.swing.JLabel pbkdf2MetaLabel;
    private javax.swing.JSpinner pbkdf2Spinner;
    // End of variables declaration//GEN-END:variables


	/**
	 * Creates new form LoginFrame
	 */
	public NewSafeFrame(final Window parent)
	{
		super(parent);
		initComponents();

		final Settings settings = Settings.getSettings();

		mainPanel.setBackground(settings.getUITheme().getBackgroundColor());

		settings.applyMetaDataFieldLabelStyle(this.pbkdf2MetaLabel);
		final JSpinner.NumberEditor editor = new JSpinner.NumberEditor(this.pbkdf2Spinner, "#");
		this.pbkdf2Spinner.setEditor(editor);
		this.pbkdf2Spinner.setValue(Integer.valueOf(1000000));

		settings.applyMetaDataFieldLabelStyle(this.password1MetaLabel);
		this.password1TextField.setText("");
		this.password1TextField.addActionListener(this);

		settings.applyMetaDataFieldLabelStyle(this.password2MetaLabel);
		this.password2TextField.setText("");
		this.password2TextField.addActionListener(this);


		settings.applyFirstButtonStyle(this.createLabel);
		this.createLabel.addMouseListener(this);


		setIconImages(settings.getFrameIcons());
		setModal(true);
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		//setSize(Toolkit.getDefaultToolkit().getScreenSize().width * 1 / 3, Toolkit.getDefaultToolkit().getScreenSize().height * 1 / 3);
		setResizable(false);
		setLocationRelativeTo(parent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        createLabel = new javax.swing.JLabel();
        pbkdf2Spinner = new javax.swing.JSpinner();
        pbkdf2MetaLabel = new javax.swing.JLabel();
        password1MetaLabel = new javax.swing.JLabel();
        password2MetaLabel = new javax.swing.JLabel();
        password1TextField = new javax.swing.JPasswordField();
        password2TextField = new javax.swing.JPasswordField();

        createLabel.setBackground(new java.awt.Color(255, 102, 0));
        createLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createLabel.setForeground(new java.awt.Color(255, 255, 255));
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLabel.setText("Create");
        createLabel.setOpaque(true);

        pbkdf2Spinner.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        pbkdf2Spinner.setModel(new javax.swing.SpinnerNumberModel(1000000, 10000, null, 1000));

        pbkdf2MetaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pbkdf2MetaLabel.setForeground(new java.awt.Color(76, 69, 69));
        pbkdf2MetaLabel.setText("PBKDF2");

        password1MetaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password1MetaLabel.setForeground(new java.awt.Color(76, 69, 69));
        password1MetaLabel.setText("Password");

        password2MetaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password2MetaLabel.setForeground(new java.awt.Color(76, 69, 69));
        password2MetaLabel.setText("Confirm Password");

        password1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password1TextField.setText("jPasswordField1");

        password2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password2TextField.setText("jPasswordField1");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(pbkdf2MetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbkdf2Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(password2MetaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(password1MetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password1TextField)))
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(createLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbkdf2MetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbkdf2Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1MetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2MetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(createLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	@Override
	public void mouseClicked(final MouseEvent mouseEvent)
	{
		final Object source = mouseEvent.getSource();
		if(source == null)
			return;

		if(source == this.createLabel)
		{
			final JFileChooser fileChooser = new JFileChooser();
			fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);


			fileChooser.setSelectedFile(new File("safe.jsb"));

			fileChooser.setFileFilter(new FileNameExtensionFilter("JSafebox file", "jsb"));
			fileChooser.setCurrentDirectory(Settings.getDefaultDirectory());

			String filename = null;
			if(fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
			{
				filename = fileChooser.getSelectedFile().toString();
				if(!filename.toUpperCase(Locale.ENGLISH).endsWith(".JSB"))
					filename += ".jsb";
			}

			if(filename == null)
				return;

			Settings.setDefaultDirectory(filename);

			final String pbkdf2IterationString = ((JSpinner.DefaultEditor) pbkdf2Spinner.getEditor()).getTextField().getText();
			final char[] pwd1 = password1TextField.getPassword();
			final char[] pwd2 = password2TextField.getPassword();

			final CreateTask task = new CreateTask(new File(filename), pbkdf2IterationString, pwd1, pwd2, GUI.getLogger());

			final ProgressFrame progressFrame = new ProgressFrame(this);
			progressFrame.execute(task);

			if(task.getException() == null)
			{
				GUI.getSettings().addSafeFilePath(filename);
				dispose();
			}
		}
	}

	@Override
	public void mousePressed(final MouseEvent mouseEvent)
	{

	}

	@Override
	public void mouseReleased(final MouseEvent mouseEvent)
	{

	}

	@Override
	public void mouseEntered(final MouseEvent e)
	{
		if(e.getSource() == null)
			return;

		if(e.getSource() == this.createLabel)
		{
			GUI.getSettings().applyFirstButtonMouseOverStyle(this.createLabel);
		}
	}

	@Override
	public void mouseExited(final MouseEvent e)
	{
		if(e.getSource() == null)
			return;

		if(e.getSource() == createLabel)
		{
			GUI.getSettings().applyFirstButtonStyle(this.createLabel);
		}
	}

	@Override
	public void actionPerformed(final ActionEvent e)
	{
		final Component component = (Component) e.getSource();

		if(component == null)
			return;

		if(component == this.password1TextField)
		{
			this.password2TextField.requestFocus();
		}
		else if(component == this.password2TextField)
		{
			final MouseEvent me = new MouseEvent(createLabel, 0, 0, 0, 0, 0, 0, 0, 0, false, 0);
			mouseClicked(me);// simulate click
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch(ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(NewSafeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(NewSafeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(NewSafeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(NewSafeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new NewSafeFrame(null).setVisible(true);
			}
		});
	}
}
