/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.ortis.jsafebox.gui;

import io.ortis.jsafebox.Safe;
import io.ortis.jsafebox.SafeFile;
import io.ortis.jsafebox.gui.old.tree.SafeFileTreeNode;
import io.ortis.jsafebox.gui.tree.SafeTreeModel;

import javax.swing.*;
import javax.swing.tree.TreeSelectionModel;
import java.awt.*;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * @author aurelien
 */
public class SafeboxFrame extends javax.swing.JFrame
{


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu ViewMenu;
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JCheckBoxMenuItem autoHashCheckBoxMenuItem;
	private javax.swing.JCheckBoxMenuItem autoSaveCheckBoxMenuItem;
	private javax.swing.JPanel belowRightPanel;
	private javax.swing.JPanel bottomPanel;
	private javax.swing.JPanel explorerPanel;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JPanel fileTreePanel;
	private javax.swing.JMenuItem hashMenuItem;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenuItem helpMenuItem;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JSplitPane jSplitPane2;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JMenuItem saveMenuItem;
	private javax.swing.JMenu securityMenu;
	private javax.swing.JCheckBoxMenuItem showPreviewCheckBoxMenuItem;
	private javax.swing.JPanel statusPanel;
	private javax.swing.JPanel topRightPanel;
	// End of variables declaration//GEN-END:variables

	private final Window parent;
	private final Safe safe;
	private final AtomicBoolean modificationPending = new AtomicBoolean(false);



	/**
	 * Creates new form SafeboxFrame
	 */
	public SafeboxFrame(final Window parent, final Safe safe)
	{
		this.parent = parent;
		this.safe = safe;

		initComponents();

		final Settings settings = Settings.getSettings();

		fileTreePanel.setBackground(settings.getColorTheme().getBackgroundColor());
		rightPanel.setBackground(settings.getColorTheme().getBackgroundColor());
		topRightPanel.setBackground(settings.getColorTheme().getBackgroundColor());
		belowRightPanel.setBackground(settings.getColorTheme().getBackgroundColor());
		bottomPanel.setBackground(settings.getColorTheme().getBackgroundColor());


		setIconImages(settings.getFrameIcons());
		setSize(Toolkit.getDefaultToolkit().getScreenSize().width * 2 / 3, Toolkit.getDefaultToolkit().getScreenSize().height * 2 / 3);
		setLocationRelativeTo(this);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	public void reloadSafe()
	{
		this.modificationPending.set(false);

		final SafeTreeModel model = new SafeTreeModel(this.safe);
		SafeFileTreeNode node = new SafeFileTreeNode(safe.getRootFolder());
		model.getRootMode().add(node);
		for (final SafeFile safeFile : safe.getRootFolder().listFiles())
			node.add(new SafeFileTreeNode(safeFile));
/*
		tree.setModel(model);
		model.reload();
		tree.expandRow(0);
		tree.repaint();

		tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);

		this.explorerFrame.setTitle(TITLE + " - " + safe.getFile().getAbsolutePath());
*/

	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		explorerPanel = new javax.swing.JPanel();
		jSplitPane1 = new javax.swing.JSplitPane();
		fileTreePanel = new javax.swing.JPanel();
		rightPanel = new javax.swing.JPanel();
		jSplitPane2 = new javax.swing.JSplitPane();
		topRightPanel = new javax.swing.JPanel();
		belowRightPanel = new javax.swing.JPanel();
		bottomPanel = new javax.swing.JPanel();
		statusPanel = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		saveMenuItem = new javax.swing.JMenuItem();
		autoSaveCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
		ViewMenu = new javax.swing.JMenu();
		showPreviewCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
		securityMenu = new javax.swing.JMenu();
		hashMenuItem = new javax.swing.JMenuItem();
		autoHashCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
		helpMenu = new javax.swing.JMenu();
		helpMenuItem = new javax.swing.JMenuItem();
		aboutMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		explorerPanel.setBackground(new java.awt.Color(255, 255, 255));

		jSplitPane1.setDividerLocation(150);
		jSplitPane1.setOneTouchExpandable(true);

		fileTreePanel.setBackground(new java.awt.Color(28, 29, 103));
		fileTreePanel.setBorder(null);
		fileTreePanel.setMinimumSize(new java.awt.Dimension(100, 0));
		fileTreePanel.setPreferredSize(new java.awt.Dimension(100, 567));

		javax.swing.GroupLayout fileTreePanelLayout = new javax.swing.GroupLayout(fileTreePanel);
		fileTreePanel.setLayout(fileTreePanelLayout);
		fileTreePanelLayout.setHorizontalGroup(fileTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));
		fileTreePanelLayout.setVerticalGroup(fileTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 572, Short.MAX_VALUE));

		jSplitPane1.setLeftComponent(fileTreePanel);

		jSplitPane2.setDividerLocation(350);
		jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
		jSplitPane2.setOneTouchExpandable(true);

		topRightPanel.setBackground(new java.awt.Color(177, 157, 24));
		topRightPanel.setBorder(null);

		javax.swing.GroupLayout topRightPanelLayout = new javax.swing.GroupLayout(topRightPanel);
		topRightPanel.setLayout(topRightPanelLayout);
		topRightPanelLayout.setHorizontalGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 975, Short.MAX_VALUE));
		topRightPanelLayout.setVerticalGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

		jSplitPane2.setTopComponent(topRightPanel);

		belowRightPanel.setBackground(new java.awt.Color(151, 246, 151));
		belowRightPanel.setBorder(null);

		javax.swing.GroupLayout belowRightPanelLayout = new javax.swing.GroupLayout(belowRightPanel);
		belowRightPanel.setLayout(belowRightPanelLayout);
		belowRightPanelLayout.setHorizontalGroup(belowRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 975, Short.MAX_VALUE));
		belowRightPanelLayout.setVerticalGroup(belowRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 566, Short.MAX_VALUE));

		jSplitPane2.setRightComponent(belowRightPanel);

		javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
		rightPanel.setLayout(rightPanelLayout);
		rightPanelLayout.setHorizontalGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane2));
		rightPanelLayout.setVerticalGroup(
				rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 572,
						Short.MAX_VALUE));

		jSplitPane1.setRightComponent(rightPanel);

		javax.swing.GroupLayout explorerPanelLayout = new javax.swing.GroupLayout(explorerPanel);
		explorerPanel.setLayout(explorerPanelLayout);
		explorerPanelLayout.setHorizontalGroup(
				explorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING));
		explorerPanelLayout.setVerticalGroup(
				explorerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572,
						Short.MAX_VALUE));

		getContentPane().add(explorerPanel, java.awt.BorderLayout.CENTER);

		bottomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
		bottomPanel.setPreferredSize(new java.awt.Dimension(1081, 35));

		statusPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
		statusPanel.setLayout(statusPanelLayout);
		statusPanelLayout.setHorizontalGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1067, Short.MAX_VALUE));
		statusPanelLayout.setVerticalGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 21, Short.MAX_VALUE));

		javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
		bottomPanel.setLayout(bottomPanelLayout);
		bottomPanelLayout.setHorizontalGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1071, Short.MAX_VALUE).addGroup(
				bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		bottomPanelLayout.setVerticalGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 25, Short.MAX_VALUE).addGroup(
				bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

		fileMenu.setText("File");

		saveMenuItem.setText("Save");
		fileMenu.add(saveMenuItem);

		autoSaveCheckBoxMenuItem.setSelected(true);
		autoSaveCheckBoxMenuItem.setText("Auto save");
		fileMenu.add(autoSaveCheckBoxMenuItem);

		jMenuBar1.add(fileMenu);

		ViewMenu.setText("View");

		showPreviewCheckBoxMenuItem.setSelected(true);
		showPreviewCheckBoxMenuItem.setText("Show preview");
		ViewMenu.add(showPreviewCheckBoxMenuItem);

		jMenuBar1.add(ViewMenu);

		securityMenu.setText("Security");

		hashMenuItem.setText("Compute hash");
		securityMenu.add(hashMenuItem);

		autoHashCheckBoxMenuItem.setSelected(true);
		autoHashCheckBoxMenuItem.setText("Check hash on opening");
		securityMenu.add(autoHashCheckBoxMenuItem);

		jMenuBar1.add(securityMenu);

		helpMenu.setText("Help");

		helpMenuItem.setText("Help frame");
		helpMenu.add(helpMenuItem);

		aboutMenuItem.setText("About");
		helpMenu.add(aboutMenuItem);

		jMenuBar1.add(helpMenu);

		setJMenuBar(jMenuBar1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch(ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(SafeboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(SafeboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(SafeboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(SafeboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new SafeboxFrame(null, null).setVisible(true);
			}
		});
	}

}
